export const SET_CARD_DATA: string = 'SET_CARD_DATA';
export const UPLOAD_CARD_DATA_REQUEST: string = 'UPLOAD_CARD_DATA_REQUEST';
export const UPLOAD_CARD_DATA_SUCCESS: string = 'UPLOAD_CARD_DATA_SUCCESS';
export const START_UPLOAD_CARD_DATA: string = 'START_UPLOAD_CARD_DATA';
