export const SET_CARD_DATA: string = 'SET_CARD_DATA';
export const UPLOADING_CARD_DATA_REQUEST: string = 'UPLOADING_CARD_DATA_REQUEST';
export const UPLOADING_CARD_DATA_SUCCESS: string = 'UPLOADING_CARD_DATA_SUCCESS';
export const START_FETCHING_CARD_DATA: string = 'START_FETCHING_CARD_DATA';
export const UPLOADING_CARD_DATA_ERROR: string = 'UPLOADING_CARD_DATA_ERROR';
export const GET_CARD_DATA: string = 'GET_CARD_DATA';
